// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta2

import (
	api "github.com/SataQiu/k8s-scheduler-example/api"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*NodeMemoryUsageLimitArgs)(nil), (*api.NodeMemoryUsageLimitArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_NodeMemoryUsageLimitArgs_To_api_NodeMemoryUsageLimitArgs(a.(*NodeMemoryUsageLimitArgs), b.(*api.NodeMemoryUsageLimitArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.NodeMemoryUsageLimitArgs)(nil), (*NodeMemoryUsageLimitArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_NodeMemoryUsageLimitArgs_To_v1beta2_NodeMemoryUsageLimitArgs(a.(*api.NodeMemoryUsageLimitArgs), b.(*NodeMemoryUsageLimitArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_NodeMemoryUsageLimitArgs_To_api_NodeMemoryUsageLimitArgs(in *NodeMemoryUsageLimitArgs, out *api.NodeMemoryUsageLimitArgs, s conversion.Scope) error {
	out.NodeMemoryUsageLimit = in.NodeMemoryUsageLimit
	return nil
}

// Convert_v1beta2_NodeMemoryUsageLimitArgs_To_api_NodeMemoryUsageLimitArgs is an autogenerated conversion function.
func Convert_v1beta2_NodeMemoryUsageLimitArgs_To_api_NodeMemoryUsageLimitArgs(in *NodeMemoryUsageLimitArgs, out *api.NodeMemoryUsageLimitArgs, s conversion.Scope) error {
	return autoConvert_v1beta2_NodeMemoryUsageLimitArgs_To_api_NodeMemoryUsageLimitArgs(in, out, s)
}

func autoConvert_api_NodeMemoryUsageLimitArgs_To_v1beta2_NodeMemoryUsageLimitArgs(in *api.NodeMemoryUsageLimitArgs, out *NodeMemoryUsageLimitArgs, s conversion.Scope) error {
	out.NodeMemoryUsageLimit = in.NodeMemoryUsageLimit
	return nil
}

// Convert_api_NodeMemoryUsageLimitArgs_To_v1beta2_NodeMemoryUsageLimitArgs is an autogenerated conversion function.
func Convert_api_NodeMemoryUsageLimitArgs_To_v1beta2_NodeMemoryUsageLimitArgs(in *api.NodeMemoryUsageLimitArgs, out *NodeMemoryUsageLimitArgs, s conversion.Scope) error {
	return autoConvert_api_NodeMemoryUsageLimitArgs_To_v1beta2_NodeMemoryUsageLimitArgs(in, out, s)
}
