// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMemoryUsageLimitArgs) DeepCopyInto(out *NodeMemoryUsageLimitArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMemoryUsageLimitArgs.
func (in *NodeMemoryUsageLimitArgs) DeepCopy() *NodeMemoryUsageLimitArgs {
	if in == nil {
		return nil
	}
	out := new(NodeMemoryUsageLimitArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeMemoryUsageLimitArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
